// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuKElAThqClXiCC1DJtuVngRt-9Vkv5fU',
    appId: '1:190781841078:web:e0d2e369da95032a649017',
    messagingSenderId: '190781841078',
    projectId: 'loginapps-17d4d',
    authDomain: 'loginapps-17d4d.firebaseapp.com',
    databaseURL: 'https://loginapps-17d4d-default-rtdb.firebaseio.com',
    storageBucket: 'loginapps-17d4d.appspot.com',
    measurementId: 'G-11W1LKT9D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHnRl4eshfoy-5XlgvBTLGWRfZHnuZxI',
    appId: '1:190781841078:android:360c6d55881eb174649017',
    messagingSenderId: '190781841078',
    projectId: 'loginapps-17d4d',
    databaseURL: 'https://loginapps-17d4d-default-rtdb.firebaseio.com',
    storageBucket: 'loginapps-17d4d.appspot.com',
  );
}
